# Generated by Django 5.2.1 on 2025-06-03 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Property price in currency units', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('square_meters', models.DecimalField(decimal_places=2, help_text='Total area in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('details', models.TextField(help_text='Detailed property description', max_length=2000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Property Inquiries',
            },
        ),
        migrations.CreateModel(
            name='PropertyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property service name', max_length=200)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Property Services',
                'ordering': ['service_type__title', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property type name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the property type')),
            ],
            options={
                'verbose_name_plural': 'Property Types',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service type name', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(auto_created=True, decimal_places=2, max_digits=10)),
                ('contract_date', models.DateField(auto_now_add=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
