# Generated by Django 5.2.1 on 2025-06-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(help_text='Type of property service', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.propertyservice'),
        ),
        migrations.AddField(
            model_name='propertyservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_services', to='catalog.servicetype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.property'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyinquiry',
            unique_together={('property', 'buyer')},
        ),
    ]
